---
title: "impact_analysis"
output: html_document
---
```{r, echo=FALSE}
setwd('/home/konstantin/documents/projects/python/text_mining/relation_extraction/journals_statistics')
rm(list=ls())
```
Рассмотрим журналы тех предложений, которые выделил наш парсер:

```{r}
journal_list <- scan('journal_list.txt',what=character(), sep="\n")
journal_list <- data.frame(journal=journal_list)
journal_list$n <- 1
agg_journal_list <- aggregate(journal_list$n, by=list(journal_list$journal), FUN=sum)
agg_journal_list <- agg_journal_list[order(agg_journal_list$x, decreasing=T), ]
head(agg_journal_list)
nrow(agg_journal_list)
```

Гистограмма по количеству предложений из журнала:

```{r}
barplot(agg_journal_list$x, xlab='Journal number', ylab='Number of sentences', main='Sentences per journal histogram')
axis(side=1)
```

Топ-20 журналов, дающих нам более половины всех предложений:

```{r}
par(las=2)
par(mar=c(4,18,1,2))
barplot(agg_journal_list$x[20:1],names.arg=agg_journal_list$Group.1[20:1],horiz=TRUE, xlab='Number of sentences',col='lightblue')
sum(agg_journal_list$x[20:1])
sum(agg_journal_list$x)
```

Теперь рассмотрим импакты этих журналов

Импакты взял отсюда: https://gisday.wordpress.com/2015/06/19/2015-journal-impact-factor-released/

```{r}
impact_list <- read.table('impact_list.txt', sep="\n", na.string=c("NO IMPACT"))
length(impact_list[!is.na(impact_list)])
length(impact_list[is.na(impact_list)])
```

4146 предложений из журналов, которые вообще не индексируются(это не плохо)

```{r}
colnames(impact_list) <- c('impact')
impact_list$impact <- as.numeric(as.character(impact_list$impact))
```

Гистограмма распределения импактов:

```{r, fig.height=5, fig.width=10}
par(las=2)
par(mar=c(6,6,6,6))
hist(impact_list$impact[!is.na(impact_list$impact)], breaks=50, axes=F,
    xlab='Impact', ylab='Number of sentences', main='Impact hist', col='lightgreen')
axis(side=1, at=0:50, labels=0:50)
axis(side=2, at=seq(0, 9000, 1000), labels=seq(0, 9000, 1000))
```